server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  devtools:
    remote:
      restart:
        enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ski?serverTimezone=Asia/Seoul
    username: ski
    password: skip1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  h2:
    console:
      enabled: true

weather:
  key: 5e3bf77ce9a0a4bd03da20cdf524e02d

file:
  path: C:/workspace/image/